/**
 * Issue Review Agent - Main Entry Point
 * 
 * This GitHub Action assesses issue severity using GitHub Models (LLM)
 * and applies appropriate labels and comments.
 */

import * as core from '@actions/core';
import * as github from '@actions/github';
import { IssueContext, IMPACT_DESCRIPTIONS, AssessmentResult } from './types';
import { assessIssue } from './llm-client';
import { 
  ensureLabelsExist, 
  getIssueLabels, 
  applyAssessmentLabels,
  applyManualReviewLabel,
} from './labels';
import { fetchCodeOwners, getDefaultOwners, extractTeams } from './codeowners';

/**
 * Format the assessment comment
 */
function formatAssessmentComment(
  assessment: AssessmentResult,
  author: string,
  assignedTeams: string[]
): string {
  const impactEmoji = ['', '🟢', '🔵', '🟡', '🟠', '🔴'][assessment.impact_score];
  const impactDesc = IMPACT_DESCRIPTIONS[assessment.impact_score];
  
  let comment = `## 🤖 Issue Assessment

Hey @${author}, this issue has been automatically reviewed.

### Impact Score: ${impactEmoji} **${assessment.impact_score}/5** - ${impactDesc}

### Summary
${assessment.summary}

### Rationale
${assessment.rationale}
`;

  if (assessment.suggested_actions.length > 0) {
    comment += `
### Suggested Actions
${assessment.suggested_actions.map(action => `- ${action}`).join('\n')}
`;
  }

  if (assignedTeams.length > 0) {
    comment += `
### Assigned Team(s)
${assignedTeams.join(', ')}
`;
  }

  comment += `
---
*This assessment was generated automatically by the Issue Review Agent. If you believe this assessment is incorrect, add the \`re-assess\` label to trigger a new review.*`;

  return comment;
}

/**
 * Format error comment
 */
function formatErrorComment(author: string, error: Error): string {
  return `## ⚠️ Assessment Failed

Hey @${author}, the automated issue review could not be completed.

### Error Details
\`\`\`
${error.message}

${error.stack || 'No stack trace available'}
\`\`\`

This issue has been labeled with \`needs-manual-review\`. A maintainer will review this issue manually.

---
*This message was generated by the Issue Review Agent.*`;
}

/**
 * Main action logic
 */
async function run(): Promise<void> {
  try {
    // Get inputs
    const token = core.getInput('github-token', { required: true });
    const issueNumber = parseInt(core.getInput('issue-number', { required: true }), 10);
    const issueTitle = core.getInput('issue-title', { required: true });
    const issueBody = core.getInput('issue-body') || '';
    const issueAuthor = core.getInput('issue-author', { required: true });
    const repository = core.getInput('repository', { required: true });

    const [owner, repo] = repository.split('/');
    
    core.info(`Reviewing issue #${issueNumber}: ${issueTitle}`);

    // Initialize GitHub client
    const octokit = github.getOctokit(token);

    // Ensure labels exist
    await ensureLabelsExist(octokit, owner, repo);

    // Get current labels
    const currentLabels = await getIssueLabels(octokit, owner, repo, issueNumber);
    
    // Build issue context
    const issueContext: IssueContext = {
      number: issueNumber,
      title: issueTitle,
      body: issueBody,
      author: issueAuthor,
      repository,
      labels: currentLabels,
    };

    // Fetch CODEOWNERS and get default team
    const codeOwners = await fetchCodeOwners(octokit, owner, repo);
    const defaultOwners = getDefaultOwners(codeOwners);
    const teams = extractTeams(defaultOwners);

    core.info('Calling GitHub Models for assessment...');

    // Assess the issue using LLM
    const assessment = await assessIssue(issueContext, token);
    
    core.info(`Assessment complete: Impact Score ${assessment.impact_score}/5`);

    // Apply labels
    await applyAssessmentLabels(octokit, owner, repo, issueNumber, assessment.impact_score, currentLabels);

    // Assign teams if available
    if (teams.length > 0) {
      try {
        // Teams are in format @org/team-name, extract just team-name
        const teamSlugs = teams.map(t => t.replace(/^@[^/]+\//, ''));
        
        // Note: Assigning teams requires the issue to be in an org repo
        // and proper permissions. We'll try but handle failure gracefully.
        for (const team of teamSlugs) {
          try {
            await octokit.rest.teams.addOrUpdateRepoPermissionsInOrg({
              org: owner,
              team_slug: team,
              owner,
              repo,
              permission: 'push',
            });
          } catch {
            core.debug(`Could not update team permissions for ${team}`);
          }
        }
      } catch (error) {
        core.warning('Could not assign teams - this may require organization permissions');
      }
    }

    // Post comment
    const comment = formatAssessmentComment(assessment, issueAuthor, teams);
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body: comment,
    });

    core.info('Assessment comment posted successfully');

    // Set outputs
    core.setOutput('impact-score', assessment.impact_score.toString());
    core.setOutput('summary', assessment.summary);

  } catch (error) {
    const err = error instanceof Error ? error : new Error(String(error));
    core.error(`Action failed: ${err.message}`);

    // Try to post error comment and apply manual review label
    try {
      const token = core.getInput('github-token', { required: true });
      const issueNumber = parseInt(core.getInput('issue-number', { required: true }), 10);
      const issueAuthor = core.getInput('issue-author', { required: true });
      const repository = core.getInput('repository', { required: true });
      const [owner, repo] = repository.split('/');

      const octokit = github.getOctokit(token);

      // Apply manual review label
      await applyManualReviewLabel(octokit, owner, repo, issueNumber);

      // Post error comment
      const errorComment = formatErrorComment(issueAuthor, err);
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: issueNumber,
        body: errorComment,
      });

      core.info('Error comment posted and manual-review label applied');
    } catch (commentError) {
      core.error(`Failed to post error comment: ${commentError}`);
    }

    core.setFailed(err.message);
  }
}

run();
